# Site settings
title:          Mughie Ams
baseurl:        ""
url:            "https://mughieams.com"

# Google Analytics
google_analytics: UA-154360741-1

# Author
author:
  name:         Mughie Arief
  url:          https://mughieams.com
  email:        mughieams24@gmail.com
  github:       mughieams
  twitter:      mughieams
  instagram:    mughieams
  linkedin:     mughieams


# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, comte.gemspec ]
