version: 2
jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
    steps:
      - checkout
      - run: npm install
      - run:
          name: Configure Bundler
          command: |
            gem install bundler -v 2.1.2
      - run: bundle install
      - run: bundle exec jekyll build
workflows:
  version: 2
  build:
    jobs:
      - deploy
