defaults: &defaults
  working_directory: ~/repo
version: 2
jobs:
  bundle_dependencies:  
    <<: *defaults
    docker:
      - image: circleci/ruby:2.7.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo      
      - restore_cache:
          keys:
            - rubygems-v1-{{ checksum "Gemfile.lock" }}
      - run: bundle config set path 'vendor/bundle'
      - run: bundle install
      - save_cache:
          key: rubygems-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/repo/vendor/bundle
      - persist_to_workspace:
          root: .
          paths: 
            - vendor/bundle
  
  build:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.7.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: bundle config set path 'vendor/bundle'
      - run: bundle
      - run: 
          name: Build Jekyll
          command: |
            bundle exec rake build
      - persist_to_workspace:
          root: .
          paths:
            - _site
            - Rakefile
  
  test_html:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.7.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: bundle config set path 'vendor/bundle'
      - run: bundle
      - run:
          name: HTMLProofer Test HTML File
          command: |
            bundle exec rake test_html
  
  test_structure:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.7.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: bundle config set path 'vendor/bundle'
      - run: bundle
      - run:
          name: HTMLProofer Test Structure Post
          command: |
            bundle exec rake test_structure
  
  deploy:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.7.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Configure Git
          command: |
            git config --global user.email "mughieams24@gmail.com"
            git config --global user.name "mughieams"
      - run:
          name: Create Commit
          command: |
            git add ~/repo/_site/.
            git commit -m "automated deployment to GitHub Pages"
      - run:
          name: Deploy site to Github Pages
          command: |
            git push https://${GITHUB_TOKEN}@github.com/mughieams/comte `git subtree split --prefix dist master`:refs/heads/gh-pages --force &> /dev/null
  
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - bundle_dependencies:
          filters:
            branches:
              ignore:
                - gh-pages
      - build:
          requires:
            - bundle_dependencies
      - test_html:
          requires:
            - build
      - test_structure:
          requires:
            - build
      - deploy:
          requires:
            - test_html
            - test_structure
          filters:
            branches:
              only: master
